# Generated by Django 2.1.11 on 2020-06-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_pk', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=100)),
                ('bill_title', models.CharField(max_length=100)),
                ('chamber_intro', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('chief_patron', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('house_patrons', models.TextField()),
                ('senate_patrons', models.TextField(blank=True)),
                ('fulltext_i', models.TextField(blank=True)),
                ('fulltext_p', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('year', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='VirginiaPolicyDatabaseApp.Session'),
        ),
    ]
